# Theme settings
remote_theme: allejo/jekyll-docs-theme

# Project information
name: fastGxE
description: "A scalable and fast multivariate GxE analysis tool."

project:
  version: 1.0.0
  download_url: https://github.com/chaoning/fastGxE
  download_text: "Download fastGxE"

# License information
license:
  software: MIT
  software_url: https://mit-license.org/

collections:
  documentation:
    output: true
    permalink: /documentation/:name/
  
# Navigation menu
nav:
  - title: "About"
    url: /documentation/01_About
  - title: "Installation"
    url: /documentation/02_installation
  - title: "Data Input"
    url: /documentation/03_data
  - title: "Tutorial"
    url: /documentation/04_Tutorial
  - title: "Experiments"
    url: /documentation/05_Experiments


# Navigation links
links:
  header:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/chaoning/fastGxE
  homepage:
    - title: "View on GitHub"
      icon: github
      brand: true
      url: https://github.com/chaoning/fastGxE
  footer:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/chaoning/fastGxE
    - title: Report Issues
      icon: bug
      url: https://github.com/chaoning/fastGxE/issues

# UI theme settings
ui:
  mode: 'auto'  # Options: 'auto', 'dark', 'light'
  brand:
    dark: "#00ceff"
    light: "#d32f2f"  # Adjusted to a softer red
  border_color:
    dark: "#5f5f5f"
    light: "#dee2e6"
  header:
    trianglify: true
    dark:
      color1: "#0a1f33"  # Adjusted for a more cohesive color scheme
      color2: "#2c4964"
    light:
      color1: "#1b0530"
      color2: "#88435c"
  masthead:
    color:
      dark: "#ffffff"
      light: "#ffffff"
    align:
      homepage: "center"
      page: "left"

# Social media links
social:
  github:
    user: chaoning
    repo: fastGxE
  twitter:
    enabled: false  # Set to false to disable Twitter integration
  facebook:
    enabled: false  # Set to false to disable Facebook integration

# Website analytics
analytics:
  google: "UA-123456-1"  # Replace with your actual Google Analytics tracking ID

# Markdown parser
markdown: kramdown

# Exclude unnecessary files to improve build performance
exclude:
  - LICENSE.md
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
